### ISSUE TITLE
"Simple Page Rename" doesn't move media files

### ISSUE THREAD

**Issue by jpicam** [michitux/dokuwiki-plugin-move#269] opened 2024-02-09 14:15 UTC
Hello,

"Simple Page Rename" don't move media files. 
Media file stay in the draft folder where all simple users can upload (or modify) new files.
We would like to move automatically media files when we move a page to an ACL restricted folder.

Indeed, we have a read-write playground zone for simple users and a read-only zone for these simple users.
Only an administrator validate and move pages from write-allowed playground zone to the read-only zone. 

Maybe, It's just the normal behavior of the "Simple page rename".
So, how to simply move all media files in same time of the page ?

Thank you,
Regards,

**Comment by splitbrain** [comment] 2024-04-03 06:32
duplicate of #222

**Closed by splitbrain** 2024-04-03 06:32 UTC
Labels: duplicate
