### ISSUE TITLE
when i read dokuwiki media (*.jpg) on the smartphone, There is a log message as below.

### ISSUE THREAD

**Issue by JoBongHyeon** [michitux/dokuwiki-plugin-move#236] opened 2023-04-22 01:04 UTC
when i read dokuwiki media (*.jpg) on the smartphone, There is a log message as below.

Warning: Undefined array key "move_renameokay" in /home1/..../lib/plugins/move/action/rename.php on line 71

**Comment by Miro-Collas** [comment] 2023-08-14 02:51
Not sure smartphone is relevant, as I'm seeing the same thing, pure desktop:

'2023-08-14 02:39:41E_WARNING: Undefined array key "move_renameokay"/home/fswiki/public_html/lib/plugins/move/action/rename.php(71)
    #0 /home/fswiki/public_html/lib/plugins/move/action/rename.php(71): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 71)
    #1 /home/fswiki/public_html/inc/Extension/EventHandler.php(80): action_plugin_move_rename->addsvgbutton(Object(dokuwiki\Extension\Event), Array)
    #2 /home/fswiki/public_html/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'AFTER')
    #3 /home/fswiki/public_html/inc/Extension/Event.php(136): dokuwiki\Extension\Event->advise_after()
    #4 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger(Array, true)
    #5 /home/fswiki/public_html/inc/Menu/AbstractMenu.php(46): dokuwiki\Extension\Event::createAndTrigger('MENU_ITEMS_ASSE...', Array, Array)
    #6 /home/fswiki/public_html/lib/tpl/bootstrap3/Template.php(2328): dokuwiki\Menu\AbstractMenu->getItems()
    #7 /home/fswiki/public_html/lib/tpl/bootstrap3/Template.php(36): dokuwiki\template\bootstrap3\Template->initToolsMenu()
    #8 /home/fswiki/public_html/lib/tpl/bootstrap3/Template.php(120): dokuwiki\template\bootstrap3\Template->__construct()
    #9 /home/fswiki/public_html/lib/tpl/bootstrap3/tpl/global.php(32): dokuwiki\template\bootstrap3\Template::getInstance()
    #10 /home/fswiki/public_html/lib/tpl/bootstrap3/mediamanager.php(13): require_once('/home/fswiki/pu...')
    #11 /home/fswiki/public_html/lib/exe/mediamanager.php(128): include('/home/fswiki/pu...')
    #12 {main}'

**Comment by michitux** [comment] 2024-05-07 21:15
Duplicate of #251, should be fixed now.

**Closed by michitux** 2024-05-07 21:15 UTC
