### ISSUE TITLE
Empty namespaces are not deleted

### ISSUE THREAD

**Issue by splitbrain** [michitux/dokuwiki-plugin-move#48] opened 2015-09-01 14:28 UTC
When all documents are moved out of a namespace, that namespace is not deleted.

@micgro42 can you please have a look at that?

**Comment by micgro42** [comment] 2015-09-04 11:59
I'm unable to reproduce this issue. It works for me, both in unittests and when testing by hand. You can find my unittests at https://github.com/micgro42/dokuwiki-plugin-move/tree/emptyDirFix

Could you elaborate on the steps to reproduce the issue?

**Comment by TorMec** [comment] 2015-12-04 15:49
It works for me too.
My test:
1) created (manually) an empty folder in /data/pages/../ and a file (not empty) in a different folder;
2) using the form (I can't with the "tree-based move manager" see #17) I've moved the file in the empty folder;
3) usign the form or the "tree-based move manager" I've emptied the folder
4) the folder has been deleted

**Comment by michitux** [comment] 2017-01-03 22:15
Can't be reproduced, no more feedback - closing.

**Closed by michitux** 2017-01-03 22:15 UTC
