### ISSUE TITLE
Move single Page does not move media images....

### ISSUE THREAD

**Issue by rgleason** [michitux/dokuwiki-plugin-move#273] opened 2024-04-02 21:55 UTC
> This plugin allows to move pages and namespaces including media files and automatically adjusts all links and media references that point to these pages. 

I am finding that the MOVE (single page) does not move my images on that page to the new "standard" locations.

Is there a specific way to accomplish this?
(Note: the source Pages images are NOT in the "standard" location.

I would very much like this to happen.

OR I would like an image "Move" or "Copy" tool that allows me to make the operation from the OLD page to the NEW page, or from the OLD (NON-standard location) to the NEW (standard location).

**Comment by splitbrain** [comment] 2024-04-03 06:33
duplicate of #222

**Closed by splitbrain** 2024-04-03 06:33 UTC
Labels: duplicate
